/*
 * 本文件由 scripts/generate-skill-library.mjs 自动生成。
 * 请勿手工编辑。
 */

export interface SkillLibraryEntry {
  id: string;
  level: string;
  typePart: string;
  fullMark: number;
  skill: string;
  advice: string;
  tips: string[];
  cautions: string[];
  drills: string[];
  acceptance: string[];
}

export const SKILL_LIBRARY_ENTRIES: SkillLibraryEntry[] = [
  {
    "id": "FCE_L-Pt1",
    "level": "FCE",
    "typePart": "L-Pt1",
    "fullMark": 8,
    "skill": "[听力] 短篇多选 (主旨/细节)",
    "advice": "听出说话人的意图、情感或场景，注意转折词后的真实含义。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_L-Pt2",
    "level": "FCE",
    "typePart": "L-Pt2",
    "fullMark": 10,
    "skill": "[听力] 句子填空",
    "advice": "必须填入原文听到的词(Exact word)，注意单复数和词性变化。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_L-Pt3",
    "level": "FCE",
    "typePart": "L-Pt3",
    "fullMark": 5,
    "skill": "[听力] 多项匹配",
    "advice": "听懂这5个人的共同主题中的不同观点，避免被个别匹配词误导。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_L-Pt4",
    "level": "FCE",
    "typePart": "L-Pt4",
    "fullMark": 7,
    "skill": "[听力] 长篇访谈 (多选)",
    "advice": "跟踪采访者的提问逻辑，区分事实陈述与个人观点。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt1",
    "level": "FCE",
    "typePart": "R-Pt1",
    "fullMark": 8,
    "skill": "[语用] 完形填空 (多选)",
    "advice": "重点积累固定搭配(Collocations)、短语动词和近义词辨析。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt2",
    "level": "FCE",
    "typePart": "R-Pt2",
    "fullMark": 8,
    "skill": "[语用] 开放式填空",
    "advice": "纯语法考核，关注介词、连词、冠词及代词的上下文指代。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt3",
    "level": "FCE",
    "typePart": "R-Pt3",
    "fullMark": 8,
    "skill": "[语用] 构词法 (Word Formation)",
    "advice": "扩大词汇族(Word Families)积累，熟悉前缀、后缀及词性转换。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt4",
    "level": "FCE",
    "typePart": "R-Pt4",
    "fullMark": 12,
    "skill": "[语用] 句型转换 (Key Word)",
    "advice": "熟练掌握被动语态、虚拟语气、直接/间接引语及倒装句。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt5",
    "level": "FCE",
    "typePart": "R-Pt5",
    "fullMark": 12,
    "skill": "[阅读] 长篇阅读 (多选)",
    "advice": "分析文章结构，推断作者观点与态度，学会排除干扰项。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt6",
    "level": "FCE",
    "typePart": "R-Pt6",
    "fullMark": 12,
    "skill": "[阅读] 句子还原 (七选六)",
    "advice": "极度考验逻辑！圈画代词(it/they)、连接词(however/so)来锁定位置。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_R-Pt7",
    "level": "FCE",
    "typePart": "R-Pt7",
    "fullMark": 10,
    "skill": "[阅读] 多项匹配 (长文)",
    "advice": "练习快速扫描(Scanning)，寻找题目与文中信息的同义替换。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_W-Pt1",
    "level": "FCE",
    "typePart": "W-Pt1",
    "fullMark": 20,
    "skill": "[写作] 议论文 (Essay)",
    "advice": "结构必须严谨(首尾呼应)，使用正式语体，必须覆盖给定的两个观点及自己的观点。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FCE_W-Pt2",
    "level": "FCE",
    "typePart": "W-Pt2",
    "fullMark": 20,
    "skill": "[写作] 多体裁选择 (文章/信件等)",
    "advice": "准确判断读者对象(Audience)和语体(Register)，格式必须规范。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_L-Pt1",
    "level": "Flyers",
    "typePart": "L-Pt1",
    "fullMark": 5,
    "skill": "[听力] 听音辨人 (连线)",
    "advice": "场景更复杂，注意区分相似人物的细微差别 (如头发、配饰)。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_L-Pt2",
    "level": "Flyers",
    "typePart": "L-Pt2",
    "fullMark": 5,
    "skill": "[听力] 听取细节并填空",
    "advice": "信息量增加，注意快速书写，拼写必须准确。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_L-Pt3",
    "level": "Flyers",
    "typePart": "L-Pt3",
    "fullMark": 5,
    "skill": "[听力] 物品/人物匹配",
    "advice": "听力材料较长，需在脑海中快速建立物品与人的对应关系。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_L-Pt4",
    "level": "Flyers",
    "typePart": "L-Pt4",
    "fullMark": 5,
    "skill": "[听力] 听取细节 (选择题)",
    "advice": "干扰项增多，需听完完整对话再做判断，不要听到单词就选。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_L-Pt5",
    "level": "Flyers",
    "typePart": "L-Pt5",
    "fullMark": 5,
    "skill": "[听力] 听音涂色与书写",
    "advice": "听指令更加复杂，涉及物体具体部位的涂色或写词。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt1",
    "level": "Flyers",
    "typePart": "RW-Pt1",
    "fullMark": 10,
    "skill": "[读写] 词汇定义匹配",
    "advice": "词汇量要求高，需准确理解长句定义的含义。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt2",
    "level": "Flyers",
    "typePart": "RW-Pt2",
    "fullMark": 5,
    "skill": "[读写] 补全对话",
    "advice": "逻辑性增强，需根据前言后语推断缺失的句子。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt3",
    "level": "Flyers",
    "typePart": "RW-Pt3",
    "fullMark": 6,
    "skill": "[读写] 完形填空 (选词)",
    "advice": "考察词汇辨析和固定搭配，注意上下文连贯性。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt4",
    "level": "Flyers",
    "typePart": "RW-Pt4",
    "fullMark": 10,
    "skill": "[读写] 语法填空 (无选项)",
    "advice": "难度较高，需自主填写介词、连词、代词等虚词。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt5",
    "level": "Flyers",
    "typePart": "RW-Pt5",
    "fullMark": 7,
    "skill": "[读写] 阅读故事补全句子",
    "advice": "概括能力要求提升，需归纳文章信息来填空。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt6",
    "level": "Flyers",
    "typePart": "RW-Pt6",
    "fullMark": 5,
    "skill": "[读写] 完形填空 (无选项)",
    "advice": "类似于Part 4，但通常考察更具功能性的语法点。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "FLYERS_RW-Pt7",
    "level": "Flyers",
    "typePart": "RW-Pt7",
    "fullMark": 1,
    "skill": "[读写] 看图写作文",
    "advice": "观察三幅图，运用连接词编写一个有逻辑的短故事 (20词+)。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_L-Pt1",
    "level": "KET",
    "typePart": "L-Pt1",
    "fullMark": 5,
    "skill": "[听力] 多选 (关键信息)",
    "advice": "警惕干扰项，通常听到的第一个选项是错误的，听完整再选。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_L-Pt2",
    "level": "KET",
    "typePart": "L-Pt2",
    "fullMark": 5,
    "skill": "[听力] 填空 (信息记录)",
    "advice": "强化数字、价格、日期、拼写的听写训练。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_L-Pt3",
    "level": "KET",
    "typePart": "L-Pt3",
    "fullMark": 5,
    "skill": "[听力] 长对话 (具体信息)",
    "advice": "听懂对话中的观点和态度，注意同义转换。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_L-Pt4",
    "level": "KET",
    "typePart": "L-Pt4",
    "fullMark": 5,
    "skill": "[听力] 听主旨/观点",
    "advice": "不要纠结个别词，听懂说话人的主要意图或感受。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_L-Pt5",
    "level": "KET",
    "typePart": "L-Pt5",
    "fullMark": 5,
    "skill": "[听力] 匹配题",
    "advice": "边听边记笔记，排除法是个好工具。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_R-Pt1",
    "level": "KET",
    "typePart": "R-Pt1",
    "fullMark": 6,
    "skill": "[阅读] 短讯息主旨理解",
    "advice": "关注生活中的标识、短信，练习找出关键词的同义替换。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_R-Pt2",
    "level": "KET",
    "typePart": "R-Pt2",
    "fullMark": 3,
    "skill": "[阅读] 三选一匹配 (细节)",
    "advice": "练习快速定位，注意题目描述与原文细节的对应。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_R-Pt3",
    "level": "KET",
    "typePart": "R-Pt3",
    "fullMark": 3,
    "skill": "[阅读] 长文主旨理解",
    "advice": "提升长难句阅读能力，关注段落大意和作者态度。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_R-Pt4",
    "level": "KET",
    "typePart": "R-Pt4",
    "fullMark": 6,
    "skill": "[阅读] 完形填空 (词汇)",
    "advice": "积累名词、形容词、动词的常见搭配及近义词辨析。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_R-Pt5",
    "level": "KET",
    "typePart": "R-Pt5",
    "fullMark": 6,
    "skill": "[阅读] 开放式填空 (语法)",
    "advice": "纯语法考核，重点强化介词、代词、连词和时态助动词。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_R-Pt6",
    "level": "KET",
    "typePart": "R-Pt6",
    "fullMark": 0,
    "skill": "[N/A] KET无此题型",
    "advice": "此级别不包含该部分。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_W-Pt1",
    "level": "KET",
    "typePart": "W-Pt1",
    "fullMark": 15,
    "skill": "[写作] 短邮件/便条",
    "advice": "必须覆盖所有3个要点，注意语域恰当，无拼写语法错误。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "KET_W-Pt2",
    "level": "KET",
    "typePart": "W-Pt2",
    "fullMark": 15,
    "skill": "[写作] 看图写故事",
    "advice": "运用 linking words (so, because) 串联图片，注意过去时态。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_L-Pt1",
    "level": "Movers",
    "typePart": "L-Pt1",
    "fullMark": 5,
    "skill": "[听力] 听音辨人 (连线)",
    "advice": "听前先看图，注意人物的衣着颜色和动作特征。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_L-Pt2",
    "level": "Movers",
    "typePart": "L-Pt2",
    "fullMark": 5,
    "skill": "[听力] 听取细节并填空",
    "advice": "重点练习拼写人名、地名以及抓取数字信息。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_L-Pt3",
    "level": "Movers",
    "typePart": "L-Pt3",
    "fullMark": 5,
    "skill": "[听力] 图片匹配 (星期/活动)",
    "advice": "听完整的句子，注意区分过去几天做了什么，留意干扰项。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_L-Pt4",
    "level": "Movers",
    "typePart": "L-Pt4",
    "fullMark": 5,
    "skill": "[听力] 听取细节 (选择题)",
    "advice": "每个小题都是一个小故事，注意听转折词 (but, no)。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_L-Pt5",
    "level": "Movers",
    "typePart": "L-Pt5",
    "fullMark": 5,
    "skill": "[听力] 听音涂色与书写",
    "advice": "区分位置介词，准确找到需要涂色的物体，只涂色不画画。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt1",
    "level": "Movers",
    "typePart": "RW-Pt1",
    "fullMark": 5,
    "skill": "[读写] 词汇定义匹配",
    "advice": "积累名词定义，注意区分功能相似的物品 (如不同种类的动物)。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt2",
    "level": "Movers",
    "typePart": "RW-Pt2",
    "fullMark": 6,
    "skill": "[读写] 补全对话",
    "advice": "结合上下文语境，注意问句和答句的时态一致性。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt3",
    "level": "Movers",
    "typePart": "RW-Pt3",
    "fullMark": 6,
    "skill": "[读写] 完形填空 (选词)",
    "advice": "通读全文掌握大意，根据词性判断空格处应填名词还是动词。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt4",
    "level": "Movers",
    "typePart": "RW-Pt4",
    "fullMark": 5,
    "skill": "[读写] 多项选择 (语法)",
    "advice": "重点考核语法基础，如名词单复数、代词指代、动词形式。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt5",
    "level": "Movers",
    "typePart": "RW-Pt5",
    "fullMark": 7,
    "skill": "[读写] 阅读故事补全句子",
    "advice": "练习同义替换，答案通常直接来自文章，不要自己编造。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt6",
    "level": "Movers",
    "typePart": "RW-Pt6",
    "fullMark": 6,
    "skill": "[读写] 看图写句子",
    "advice": "仔细观察图片，回答问题并写完整的句子，注意拼写。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "MOVERS_RW-Pt7",
    "level": "Movers",
    "typePart": "RW-Pt7",
    "fullMark": 0,
    "skill": "[N/A] Movers无此题型",
    "advice": "此级别不包含该部分。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_L-Pt1",
    "level": "PET",
    "typePart": "L-Pt1",
    "fullMark": 7,
    "skill": "[听力] 多选 (关键图片)",
    "advice": "听懂具体细节，排除极具迷惑性的干扰信息。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_L-Pt2",
    "level": "PET",
    "typePart": "L-Pt2",
    "fullMark": 6,
    "skill": "[听力] 多选 (短对话)",
    "advice": "听懂说话人的态度、观点和意图。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_L-Pt3",
    "level": "PET",
    "typePart": "L-Pt3",
    "fullMark": 6,
    "skill": "[听力] 填空 (长独白)",
    "advice": "听懂说明性文字，捕捉并准确拼写关键名词或数字。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_L-Pt4",
    "level": "PET",
    "typePart": "L-Pt4",
    "fullMark": 6,
    "skill": "[听力] 多选 (长采访)",
    "advice": "听懂详细的观点阐述，理解对话深层逻辑。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_L-Pt5",
    "level": "PET",
    "typePart": "L-Pt5",
    "fullMark": 0,
    "skill": "[N/A] PET无此题型",
    "advice": "此级别不包含该部分。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_R-Pt1",
    "level": "PET",
    "typePart": "R-Pt1",
    "fullMark": 5,
    "skill": "[阅读] 短讯息主旨",
    "advice": "注意细微的情感态度差异，理解隐含意义。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_R-Pt2",
    "level": "PET",
    "typePart": "R-Pt2",
    "fullMark": 5,
    "skill": "[阅读] 人物与描述匹配",
    "advice": "阅读量大，练习划关键词，寻找完全匹配项。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_R-Pt3",
    "level": "PET",
    "typePart": "R-Pt3",
    "fullMark": 5,
    "skill": "[阅读] 长文理解 (多选)",
    "advice": "深入理解文章结构，区分事实与观点。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_R-Pt4",
    "level": "PET",
    "typePart": "R-Pt4",
    "fullMark": 5,
    "skill": "[阅读] 句子还原 (填空)",
    "advice": "逻辑性极强，需关注代词指代和上下文逻辑连接词。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_R-Pt5",
    "level": "PET",
    "typePart": "R-Pt5",
    "fullMark": 6,
    "skill": "[阅读] 完形填空 (多选)",
    "advice": "考核精准的词汇搭配、固定用法及词义辨析。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_R-Pt6",
    "level": "PET",
    "typePart": "R-Pt6",
    "fullMark": 6,
    "skill": "[阅读] 开放式填空",
    "advice": "考核语法结构，如从句引导词、固定介词搭配。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_W-Pt1",
    "level": "PET",
    "typePart": "W-Pt1",
    "fullMark": 20,
    "skill": "[写作] 邮件回复 (100词)",
    "advice": "必须回应4个要点，注意语气的得体和内容的扩展。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  },
  {
    "id": "PET_W-Pt2",
    "level": "PET",
    "typePart": "W-Pt2",
    "fullMark": 20,
    "skill": "[写作] 文章/故事",
    "advice": "文章需有清晰的结构和标题；故事需情节生动，时态准确。",
    "tips": [],
    "cautions": [],
    "drills": [],
    "acceptance": []
  }
] as const;

export const SKILL_LIBRARY_MAP: Map<string, SkillLibraryEntry> = new Map(
  SKILL_LIBRARY_ENTRIES.map((entry) => [`${entry.level}|${entry.typePart}`, entry] as const),
);
